/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

interface CounterContractAbiInterface extends Interface {
  functions: {
    increment: FunctionFragment;
    increase: FunctionFragment;
    counter: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'increment', values?: undefined): Uint8Array;
  encodeFunctionData(functionFragment: 'increase', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'counter', values?: undefined): Uint8Array;

  decodeFunctionData(functionFragment: 'increment', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'increase', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'counter', data: BytesLike): DecodedValue;
}

export class CounterContractAbi extends Contract {
  interface: CounterContractAbiInterface;
  functions: {
    increment: InvokeFunction<[], void>;

    increase: InvokeFunction<[amount: BigNumberish], void>;

    counter: InvokeFunction<[], BN>;
  };
}
