/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

export type ContractIdInput = { value: string };

export type ContractIdOutput = { value: string };

interface SwayswapContractAbiInterface extends Interface {
  functions: {
    add_exchange_contract: FunctionFragment;
    get_exchange_contract: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'add_exchange_contract',
    values: [ContractIdInput, ContractIdInput]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: 'get_exchange_contract',
    values: [ContractIdInput]
  ): Uint8Array;

  decodeFunctionData(functionFragment: 'add_exchange_contract', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_exchange_contract', data: BytesLike): DecodedValue;
}

export class SwayswapContractAbi extends Contract {
  interface: SwayswapContractAbiInterface;
  functions: {
    add_exchange_contract: InvokeFunction<
      [token_id: ContractIdInput, exchange_id: ContractIdInput],
      void
    >;

    get_exchange_contract: InvokeFunction<[token_id: ContractIdInput], ContractIdOutput>;
  };
}
