/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.28.0
  Forc version: 0.32.2
  Fuel-Core version: 0.15.1
*/

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from 'fuels';

import type { Enum } from './common';

export type ErrorInput = Enum<{ MustBeCalledByOwner: [] }>;
export type ErrorOutput = ErrorInput;

export type VaultFeeInput = {
  start_time: BigNumberish;
  start_fee: BigNumberish;
  current_fee: BigNumberish;
  change_rate: BigNumberish;
};
export type VaultFeeOutput = {
  start_time: number;
  start_fee: number;
  current_fee: number;
  change_rate: number;
};

interface VaultContractAbiInterface extends Interface {
  functions: {
    claim_fees: FunctionFragment;
    get_fees: FunctionFragment;
    set_fees: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'claim_fees', values: [string]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_fees', values: []): Uint8Array;
  encodeFunctionData(
    functionFragment: 'set_fees',
    values: [BigNumberish, BigNumberish]
  ): Uint8Array;

  decodeFunctionData(functionFragment: 'claim_fees', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_fees', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_fees', data: BytesLike): DecodedValue;
}

export class VaultContractAbi extends Contract {
  interface: VaultContractAbiInterface;
  functions: {
    claim_fees: InvokeFunction<[pool: string], void>;
    get_fees: InvokeFunction<[], VaultFeeOutput>;
    set_fees: InvokeFunction<[start_fee: BigNumberish, change_rate: BigNumberish], void>;
  };
}
