/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from 'fuels';
import { Interface, Contract } from 'fuels';
import type { CounterContractAbi, CounterContractAbiInterface } from '../CounterContractAbi';
const _abi = {
  types: [
    {
      typeId: 0,
      type: '()',
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: 'struct Increased',
      components: [
        {
          name: 'amount',
          type: 2,
          typeArguments: null,
        },
        {
          name: 'new_count',
          type: 2,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 2,
      type: 'u64',
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [],
      name: 'increment',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
    },
    {
      inputs: [
        {
          name: 'amount',
          type: 2,
          typeArguments: null,
        },
      ],
      name: 'increase',
      output: {
        name: '',
        type: 0,
        typeArguments: null,
      },
    },
    {
      inputs: [],
      name: 'counter',
      output: {
        name: '',
        type: 2,
        typeArguments: null,
      },
    },
  ],
  loggedTypes: [
    {
      logId: 165396,
      loggedType: {
        name: '',
        type: 1,
        typeArguments: [],
      },
    },
    {
      logId: 165422,
      loggedType: {
        name: '',
        type: 1,
        typeArguments: [],
      },
    },
  ],
};

export class CounterContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): CounterContractAbiInterface {
    return new Interface(_abi) as unknown as CounterContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): CounterContractAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as CounterContractAbi;
  }
}
