/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet, AbstractAddress } from 'fuels';
import { Interface, Contract } from 'fuels';
import type { SwayswapContractAbi, SwayswapContractAbiInterface } from '../SwayswapContractAbi';
const _abi = [
  {
    type: 'function',
    name: 'add_exchange_contract',
    inputs: [
      {
        type: 'struct ContractId',
        name: 'token_id',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
      {
        type: 'struct ContractId',
        name: 'exchange_id',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
    ],
    outputs: [
      {
        type: '()',
        name: '',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    name: 'get_exchange_contract',
    inputs: [
      {
        type: 'struct ContractId',
        name: 'token_id',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
    ],
    outputs: [
      {
        type: 'struct ContractId',
        name: '',
        components: [
          {
            type: 'b256',
            name: 'value',
          },
        ],
      },
    ],
  },
];

export class SwayswapContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): SwayswapContractAbiInterface {
    return new Interface(_abi) as unknown as SwayswapContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: Wallet | Provider
  ): SwayswapContractAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as SwayswapContractAbi;
  }
}
