name: "CI"

on:
  pull_request:
    types: [opened, synchronize, edited, closed]

jobs:
  cancel-previous-run:
    name: Cancel previous actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  validate-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Pull request title check
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-node
      - uses: ./.github/setup-rust

      - name: Build Sway
        run: |
          pnpm contracts:build

      - name: Test Contracts
        run: |
          ./scripts/test-contracts.sh
